version: 2.1
orbs:
  gradle: circleci/gradle@1.0.11
_defaults: &defaults
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
jobs:
  build-linux:
    docker:
      - image: circleci/openjdk:8-jdk
    <<: *defaults
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Run Tests
                command: ./gradlew test
            - gradle/collect_test_results:
                test_results_path: build/test-results
                reports_path: build/reports
            - deploy:
                command: |
                  if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    echo "$MAVEN_CENTRAL_SEC_RING" | base64 -d > $HOME/secring.gpg
                    gpg --import --batch $HOME/secring.gpg
                    ./gradlew publish -Psonatype.username="$SONATYPE_USERNAME" -Psonatype.password="$SONATYPE_PASSWORD" -Psigning.keyId=0E7A8B89 -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg -Porg.gradle.parallel=false
                  fi
  build-macos:
    macos:
      xcode: "10.2.1"
    <<: *defaults
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Run Tests
                command: ./gradlew nativeTest
            - gradle/collect_test_results:
                test_results_path: build/test-results
                reports_path: build/reports
            - deploy:
                command: |
                  if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    echo "$MAVEN_CENTRAL_SEC_RING" | base64 -d > $HOME/secring.gpg
                    gpg --import --batch $HOME/secring.gpg
                    ./gradlew publishIosArm64PublicationToMavenRepository publishIosX64PublicationToMavenRepository publishIosX64PublicationToMavenRepository publishMacosPublicationToMavenRepository -Psonatype.username="$SONATYPE_USERNAME" -Psonatype.password="$SONATYPE_PASSWORD" -Psigning.keyId=0E7A8B89 -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg -Porg.gradle.parallel=false
                  fi
workflows:
  version: 2
  build:
    jobs:
      - build-linux:
          context: opensource-maven
      - build-macos:
          context: opensource-maven
